---
version: "2"

volumes:

  ldap_conf:
  ldap_data:

  idp_credentials:
  idp_logs:

services:

  # Shibboleth IdP service for the domain
  idp:
    image: "arkivum/shibboleth-idp:${DOMAIN_NAME}"
    build:
      context: "./shib/idp/"
      args:
        - DOMAIN_NAME
    container_name: "idp.${DOMAIN_NAME}"
    hostname: "idp"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "shibnet"
    environment:
      - "JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=12345"
      - "JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=12345"
    volumes:
      - "idp_credentials:/opt/shibboleth-idp/credentials"
      - "idp_logs:/opt/shibboleth-idp/logs"
      # Provide our own IdP metadata file, configured for our SPs
      - "./am-shib/idp/build/metadata-providers.xml:/opt/shibboleth-idp/conf/metadata-providers.xml:ro"
    expose:
      - "4443"
      - "8443"
    ports:
      - "${IDP_EXTERNAL_IP}:443:4443"
    depends_on:
      - "ldap"
    links:
      - "ldap:ldap.${DOMAIN_NAME}"

  # LDAP service for the domain
  ldap:
    image: "osixia/openldap"
    hostname: "ldap"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "shibnet"
    environment:
      - "LDAP_DOMAIN=${DOMAIN_NAME}"
      - "LDAP_ORGANISATION=${DOMAIN_ORGANISATION}"
      - "LDAP_TLS=false"
    volumes:
      - "ldap_conf:/etc/ldap/"
      - "ldap_data:/var/lib/ldap/"
      - "./shib/ldap/etc/ldap/edu/:/usr/local/ldap/edu/"
      - "./shib/ldap/build/demo-users.ldif:/usr/local/ldap/demo-users.ldif:ro"
    expose:
      - "389"

  # Override main nginx config, enabling Shibboleth for Archivematica services
  # Dashboard runs on 443 and Storage Service on 8443
  nginx:
    image: "arkivum/shibboleth-nginx:${DOMAIN_NAME}"
    container_name: "archivematica.${DOMAIN_NAME}"
    hostname: "archivematica"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "default"
      - "shibnet"
    environment:
      # The hostname of the nginx server serving Archivematica
      NGINX_HOSTNAME: "archivematica.${DOMAIN_NAME}"
      # Shibboleth FastCGI SP config
      SHIBBOLETH_IDP_ENTITY_ID: "https://idp.${DOMAIN_NAME}/idp/shibboleth"
      SHIBBOLETH_IDP_METADATA_URL: "https://idp.${DOMAIN_NAME}:4443/idp/shibboleth"
    volumes:
      # Override the default nginx archivematica config with ones for Shibboleth
      - "./am-shib/nginx/etc/nginx/conf.d/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
      - "./am-shib/nginx/etc/nginx/conf.d/am-shib.inc:/etc/nginx/conf.d/am-shib.inc:ro"
      # Override the default Shibboleth attribute-map, so we get the right attributes exposed
      - "./am-shib/nginx/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro"
      # Override the default Supervisor config to add additional programs
      - "./am-shib/nginx/etc/supervisor/conf.d/shibboleth.conf:/etc/supervisor/conf.d/shibboleth.conf:ro"
    expose:
      - "443"
      - "8443"
    ports:
      - "${NGINX_EXTERNAL_IP}:443:443"
      - "${NGINX_EXTERNAL_IP}:8443:8443"
    depends_on:
      - "archivematica-dashboard"
      - "archivematica-storage-service"
    links:
      - "idp:idp.${DOMAIN_NAME}"

  archivematica-dashboard:
    environment:
      ARCHIVEMATICA_DASHBOARD_SHIBBOLETH_AUTHENTICATION: "True"

  archivematica-storage-service:
    environment:
      SS_SHIBBOLETH_AUTHENTICATION: "True"

networks:
  shibnet:
    driver: "bridge"